### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Darkle**
- Switched to using .env file for username, password and target url.
- Switched to using https instead of http.
- Updated the login button selector.
- Changed the course.name.replace to remove other characters not allowed (such as ?).

### CODE REVIEW

**Comment by ryanjerskine** [comment]
I think this repo might be dead. If you are interested in a similar scraper, feel free to do a similar pull request on https://github.com/ryanjerskine/pluralsight-scraper . If not, I might steal using the .env file if that's ok.

**Comment by vezaynk** [comment]
It's not dead until it stops working at which point I will put up some text saying "does not work, try x or y instead".

It has bugs, I do not plan on improving it anytime soon but I will gladly handle community contributions.

**Comment by vezaynk** [comment]
It all looks good. Could you explain the regex change? It should have already been stripping all undesirable characters unless if I forgot how it worked.

Anyways, I love the env stuff!

**Comment by Darkle** [comment]
> It all looks good. Could you explain the regex change? It should have already been stripping all undesirable characters unless if I forgot how it worked.

Yeah sure, I was downloading a tutorial that had a video with a question mark in its title, which seems to be a disallowed character for file names on windows. 

The regex I added says to replace anything that isn't an a-to-z character. It might be a bit of an aggressive regex so you could pair it down to maybe just replace characters that aren't allowed in file names.

**Pull request merged**
